CREATE TABLE `t_status` (
	`id` INT(3) NOT NULL AUTO_INCREMENT,
	`status` VARCHAR(50) NOT NULL COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=18
;
